# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dishwatch < Formula
  desc "Starlink dish status, dashboard and power-bank CLI over local gRPC"
  homepage "https://github.com/faeton/dishwatch"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.5/dishwatch_Darwin_x86_64.tar.gz"
      sha256 "452eb7557c16e8b96e12bc4bd3eec62fb43df960580b0cc7fb6d9f02c921c6af"

      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.5/dishwatch_Darwin_arm64.tar.gz"
      sha256 "afa93cd451d8ac44475874c2b16903f84f7cd1a752ae26837dc8ddc5ddb1d744"

      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.5/dishwatch_Linux_x86_64.tar.gz"
      sha256 "66a147baf04e6c003dcafac0a273b3c14fe2228069bbee480a25d4f4acfd297b"
      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.5/dishwatch_Linux_arm64.tar.gz"
      sha256 "66232a558b931b4bf148d40e47e37ace2da0e1b0a6b7ecad4bd79747578d563d"
      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
  end

  test do
    system bin/"dishwatch", "--version"
    system bin/"sl", "--help"
  end
end
