# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dishwatch < Formula
  desc "Starlink dish status, dashboard and power-bank CLI over local gRPC"
  homepage "https://github.com/faeton/dishwatch"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.6/dishwatch_Darwin_x86_64.tar.gz"
      sha256 "f31cf8faf852d664c6d7802f9498425b6be29ab86b892940ab475ed60fda5951"

      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.6/dishwatch_Darwin_arm64.tar.gz"
      sha256 "d2908057e6fd1c67528a4c96c2b8a670492e48785e6ad31a007db280a2999d30"

      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.6/dishwatch_Linux_x86_64.tar.gz"
      sha256 "4b8fcdcfc37c6d5858073cfb2a70d73c0f50a06205ba02d6db5c231dcee79ebb"
      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.6/dishwatch_Linux_arm64.tar.gz"
      sha256 "e55938d5db199c00f0a0ef3980e4cbe9aacaf60665f66da9700f4c03a4abc4bb"
      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
  end

  test do
    system bin/"dishwatch", "--version"
    system bin/"sl", "--help"
  end
end
