# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dishwatch < Formula
  desc "Starlink dish status, dashboard and power-bank CLI over local gRPC"
  homepage "https://github.com/faeton/dishwatch"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.4/dishwatch_Darwin_x86_64.tar.gz"
      sha256 "dbfbea4c9e8769dc0655a5541012f36066ab8520edb047e32efa71fa4a524d22"

      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.4/dishwatch_Darwin_arm64.tar.gz"
      sha256 "58a5d80eb5bd300debecf482529b341b83f8a1700f08c29bc102f9d5056a3030"

      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.4/dishwatch_Linux_x86_64.tar.gz"
      sha256 "d75b2020c09a01ea137c80a2ff94da0863be476e5273366f5823f04c9d6b6fa4"
      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faeton/dishwatch/releases/download/v0.2.4/dishwatch_Linux_arm64.tar.gz"
      sha256 "8bbb2860dd9c2afc9d5f7759d13ec5c65ebc74588c872640c4a896d8523a450f"
      define_method(:install) do
        bin.install "dishwatch"
        bin.install_symlink "dishwatch" => "sl"
      end
    end
  end

  test do
    system bin/"dishwatch", "--version"
    system bin/"sl", "--help"
  end
end
