# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sl < Formula
  desc "Tiny Starlink status CLI — talks to the local dish gRPC API"
  homepage "https://github.com/faeton/dishwatch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faeton/dishwatch/releases/download/v0.1.0/sl_Darwin_x86_64.tar.gz"
      sha256 "98fe95a2e75e3daab8bd9f0fe7b1179a1bddf5f4dbc6e59866483f8e2335caab"

      define_method(:install) do
        bin.install "sl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faeton/dishwatch/releases/download/v0.1.0/sl_Darwin_arm64.tar.gz"
      sha256 "f194c3d94a2c70a4616f16f6cebaed6789b54958b747401d2e1b3510e20fe140"

      define_method(:install) do
        bin.install "sl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faeton/dishwatch/releases/download/v0.1.0/sl_Linux_x86_64.tar.gz"
      sha256 "2b150af348e30470dc8eb8ae28d50835f070df51de20313c1c1c0faefd60e7b8"
      define_method(:install) do
        bin.install "sl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faeton/dishwatch/releases/download/v0.1.0/sl_Linux_arm64.tar.gz"
      sha256 "21b7c7da9b38fcf0ea5eba390d9fb108ab561a42623a1ff42ac716f3d92d0b4d"
      define_method(:install) do
        bin.install "sl"
      end
    end
  end

  test do
    system "#{bin}/sl", "--help"
  end
end
